# Generated by Django 5.1.2 on 2025-03-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('image', models.ImageField(upload_to='photos')),
                ('type', models.CharField(choices=[('Masala Chai', 'Masala Chai'), ('Ginger Chai', 'Ginger Chai'), ('Lemon Chai', 'Lemon Chai'), ('Black Tea', 'Black Tea'), ('Green Tea', 'Green Tea')], default='Masala Chai', max_length=15)),
            ],
        ),
    ]
