# Generated by Django 5.1.2 on 2025-04-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chai',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chai',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
